export enum SocketEvent {
  GET_CODE = 'GET_CODE',
  CREATE_PLANNING = 'CREATE_PLANNING',
  JOIN_PLANNING = 'JOIN_PLANNING',
  SELECT_CARD = 'SELECT_CARD',
  SHOW_CARDS = 'SHOW_CARDS',
  RESET_CARDS = 'RESET_CARDS',

  USER_LEAVE = 'USER_LEAVE',
  USER_JOIN = 'USER_JOIN',

  CONNECTION = 'connection',
  DISCONNECT = 'disconnect',
}
